import type { Ticket } from "./types";

export const CURRENT_USER = "Priya Sharma";

export const ISSUE_TYPES = [
  "Payment Delayed",
  "TDS Query",
  "POC / Conduct Concern",
  "GST Query",
  "Campaign Brief Clarification",
  "Content Approval Delay",
  "Contract / Agreement",
  "Other",
];

export const EXECUTIVES = [
  "Priya Sharma",
  "Rahul Mehta",
  "Ananya Iyer",
  "Vikram Desai",
  "Neha Kapoor",
];

export const SAMPLE_TICKETS: Ticket[] = [
  {
    id: "CF-2026-00001",
    ticketNumber: "CF-2026-00001",
    creatorName: "Aarav Malhotra",
    phone: "+91 98765 43210",
    email: "aarav.malhotra@email.com",
    socialHandle: "@aaravcreates",
    platform: "Instagram",
    issueType: "Payment Delayed",
    issueCategory: "Payment Delayed",
    campaignName: "Galaxy S26 Creator Launch",
    brand: "Samsung",
    campaignMonth: "July 2026",
    cloutflowPoc: "Neha Kapoor",
    cloutflowPocContactNumber: "+91 98765 43101",
    issueDescription:
      "Creator reports that the final milestone payment for the Galaxy S26 reel series has not been credited even after content went live and was approved. Invoice was submitted on 28 July.",
    sourceChannel: "WhatsApp",
    status: "Open",
    priority: "High",
    assignedTeam: "Creator Payments",
    assignedExecutive: "Priya Sharma",
    createdAt: "2026-08-08T09:15:00+05:30",
    updatedAt: "2026-08-11T10:42:00+05:30",
    activity: [
      {
        id: "a1",
        timestamp: "2026-08-08T09:15:00+05:30",
        actor: "System",
        action: "Ticket created from WhatsApp inbound.",
      },
      {
        id: "a2",
        timestamp: "2026-08-08T11:05:00+05:30",
        actor: "Priya Sharma",
        action: "Assigned to Creator Payments team and requested invoice copy.",
      },
      {
        id: "a3",
        timestamp: "2026-08-11T10:42:00+05:30",
        actor: "Priya Sharma",
        action: "Finance confirmed payment is in processing queue for today.",
      },
    ],
  },
  {
    id: "CF-2026-00002",
    ticketNumber: "CF-2026-00002",
    creatorName: "Ishita Rao",
    phone: "+91 98111 22334",
    email: "ishita.rao@email.com",
    socialHandle: "@ishitarao",
    platform: "Instagram",
    issueType: "TDS Query",
    issueCategory: "TDS Query",
    campaignName: "Himalaya Wellness Stories",
    brand: "Himalaya",
    campaignMonth: "June 2026",
    cloutflowPoc: "Rahul Mehta",
    cloutflowPocContactNumber: "+91 98765 43102",
    issueDescription:
      "Creator wants clarity on TDS deducted from the June campaign payout and whether Form 16A will be issued for FY 2026-27.",
    sourceChannel: "Instagram",
    status: "In Progress",
    priority: "Normal",
    assignedTeam: "Finance Ops",
    assignedExecutive: "Rahul Mehta",
    createdAt: "2026-08-07T14:20:00+05:30",
    updatedAt: "2026-08-10T16:05:00+05:30",
    activity: [
      {
        id: "b1",
        timestamp: "2026-08-07T14:20:00+05:30",
        actor: "System",
        action: "Ticket created from Instagram DM.",
      },
      {
        id: "b2",
        timestamp: "2026-08-08T10:10:00+05:30",
        actor: "Rahul Mehta",
        action: "Pulled payout ledger and shared TDS breakup draft.",
      },
      {
        id: "b3",
        timestamp: "2026-08-10T16:05:00+05:30",
        actor: "Rahul Mehta",
        action: "Waiting on finance for Form 16A timeline confirmation.",
      },
    ],
  },
  {
    id: "CF-2026-00003",
    ticketNumber: "CF-2026-00003",
    creatorName: "Kabir Singh",
    phone: "+91 99001 55667",
    email: "kabir.singh@email.com",
    socialHandle: "@kabirtravels",
    platform: "YouTube",
    issueType: "POC / Conduct Concern",
    issueCategory: "POC / Conduct Concern",
    campaignName: "MakeMyTrip Summer Escapes",
    brand: "MakeMyTrip",
    campaignMonth: "August 2026",
    cloutflowPoc: "Ananya Iyer",
    cloutflowPocContactNumber: "+91 98765 43103",
    issueDescription:
      "Creator raised a conduct concern regarding delayed responses and unclear briefing changes from the assigned brand POC during shoot week. Requesting escalation and a revised communication plan.",
    sourceChannel: "Website",
    status: "Waiting",
    priority: "Urgent",
    assignedTeam: "Creator Success",
    assignedExecutive: "Ananya Iyer",
    createdAt: "2026-08-09T18:40:00+05:30",
    updatedAt: "2026-08-11T09:12:00+05:30",
    activity: [
      {
        id: "c1",
        timestamp: "2026-08-09T18:40:00+05:30",
        actor: "System",
        action: "Ticket submitted via website support form.",
      },
      {
        id: "c2",
        timestamp: "2026-08-10T09:00:00+05:30",
        actor: "Ananya Iyer",
        action: "Marked Urgent and scheduled internal escalation call.",
      },
      {
        id: "c3",
        timestamp: "2026-08-11T09:12:00+05:30",
        actor: "Ananya Iyer",
        action: "Awaiting brand POC response after escalation email.",
      },
    ],
  },
  {
    id: "CF-2026-00004",
    ticketNumber: "CF-2026-00004",
    creatorName: "Meera Joshi",
    phone: "+91 97654 88990",
    email: "meera.joshi@email.com",
    socialHandle: "@meerajoshi",
    platform: "YouTube",
    issueType: "GST Query",
    issueCategory: "GST Query",
    campaignName: "Dreame Home Launch",
    brand: "Dreame",
    campaignMonth: "May 2026",
    cloutflowPoc: "Vikram Desai",
    cloutflowPocContactNumber: "+91 98765 43104",
    issueDescription:
      "Creator asked whether GST invoice is required for the Dreame campaign payout and how to update GSTIN on the creator profile.",
    sourceChannel: "Phone Call",
    status: "Resolved",
    priority: "Normal",
    assignedTeam: "Finance Ops",
    assignedExecutive: "Vikram Desai",
    createdAt: "2026-08-02T11:30:00+05:30",
    updatedAt: "2026-08-05T15:25:00+05:30",
    activity: [
      {
        id: "d1",
        timestamp: "2026-08-02T11:30:00+05:30",
        actor: "System",
        action: "Ticket logged from inbound phone call.",
      },
      {
        id: "d2",
        timestamp: "2026-08-03T12:15:00+05:30",
        actor: "Vikram Desai",
        action: "Shared GST invoice guidelines and profile update steps.",
      },
      {
        id: "d3",
        timestamp: "2026-08-05T15:25:00+05:30",
        actor: "Vikram Desai",
        action: "Creator confirmed GSTIN updated. Ticket resolved.",
      },
    ],
  },
];
